[env]
AXUM_HTTP_REQUESTS_TOTAL = "payment_service_requests_total"
AXUM_HTTP_REQUESTS_DURATION_SECONDS = "payment_service_requests_duration_seconds"
AXUM_HTTP_REQUESTS_PENDING = "payment_service_requests_pending"
AXUM_HTTP_RESPONSE_BODY_SIZE = "payment_service_response_body_size"